### PR TITLE
Add play pause options

### PR DESCRIPTION
**Pull request by brunetton**
Thanks for this great plugin ! 
Here I added useful signals to pause and continue a process. Super useful in many cases.

Hope you'll like it

### CODE REVIEW

**Comment by brunetton** [comment]
@gornostal any news ? Do you still use and/or maintain this repo ? If not, could you add me as a maintainer / collaborator ?

Thanks !

**Comment by cbenz** [comment]
It's an awesome feature! Thanks!

**Comment by gornostal** [comment]
Apologies for the delay. And thanks for the useful improvements!
Merged.

**Comment by brunetton** [comment]
Thanks. Unfortunately I don't see my name in the projects contributors :( But this is a detail; maybe there's a long delay. Have a good day

**Pull request merged**
