### PR TITLE
Revert "Revert "fixed subprocess call to work on all systems""

### PR DESCRIPTION
**Pull request by dalanicolai**
I forgot to adapt the column numbers in the for loop. Of course they should changed to the following
pid = col[0]
cpu = atof(col[1])
cmd = ' '.join(col[2:])

As said above I attached the comment again

### CODE REVIEW

**Comment by gornostal** [comment]
But it is exactly the same as the previous one, which didn't work for me.

**Comment by dalanicolai** [comment]
Yes but only the column numbers have to be changed in lines 119-121 as
mentioned in the comment. So I guess you do not receive the comment?

**Comment by dalanicolai** [comment]
The message sent with the request

**Comment by gornostal** [comment]
I do see the comment. I don't understand what it means I guess

**Comment by gornostal** [comment]
Could you make sure that this MR doesn't break anything?

**Comment by dalanicolai** [comment]
Sorry I mean the list index number. I would have very quickly done it
myself if I could still do it (without creating another pull/merge request)

**Comment by gornostal** [comment]
You don't have to create another PR. You can push new commits to this branch.

**Comment by dalanicolai** [comment]
Sorry. I do not fully understand it. I created a clean request. That should not break anything. Therefore I will close this request now.

**Pull request closed without merging**
